import configparser
import os
from langchain_google_genai import ChatGoogleGenerativeAI


def get_api_key(config_file="credentials.ini") -> str | None:
    """
    Reads the Google API key from a credentials.ini file.

    Args:
        config_file: The path to the configuration file.

    Returns:
        The API key as a string, or None if not found.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))

    parent_dir = os.path.dirname(script_dir)
    grandparent_dir = os.path.dirname(parent_dir)

    absolute_path = os.path.join(grandparent_dir, config_file)

    print(f"Looking for configuration file at: {absolute_path}")

    try:
        if not os.path.exists(absolute_path):
            raise FileNotFoundError(f"File not found at {absolute_path}")

        config = configparser.ConfigParser()
        config.read(absolute_path)

        return config['google']['api_key']

    except FileNotFoundError:
        print(f"Error: The configuration file was not found.")
        return None
    except KeyError:
        print(f"Error: Could not find 'api_key' under [google] section in '{config_file}'.")
        return None
    except configparser.MissingSectionHeaderError:
        print(f"Error: File '{absolute_path}' is empty or not a valid .ini file (missing [google] header).")
        return None


def get_gemini_response(prompt: str) -> str:
    """
    Sends a prompt to the Google Gemini model and returns the response.

    Args:
        prompt: The text you want to send to the model.

    Returns:
        The text response generated by the model or an error message.
    """
    try:
        MY_API_KEY = get_api_key()

        model = ChatGoogleGenerativeAI(model="gemini-2.0-flash", google_api_key=MY_API_KEY)

        response = model.invoke(prompt)
        print("Successfully received response from Gemini API.")
        return response.content

    except Exception as e:
        return f"An error occurred while communicating with the API: {e}"
